name: Build and deploy Node.js app to Azure Web App - andym-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: List contents of entire project directory (debugging)
        run: |
          echo "Listing contents of entire project directory:"
          Get-ChildItem -Recurse

      - name: List contents of .next directory (debugging)
        run: |
          echo "Listing contents of .next directory:"
          Get-ChildItem .next -Recurse || echo ".next directory does not exist"

      - name: List contents of .next/standalone directory (debugging)
        run: |
          echo "Listing contents of .next/standalone directory:"
          Get-ChildItem .next/standalone -Recurse || echo ".next/standalone directory does not exist"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Verify downloaded artifact contents
        run: |
        
